name: 自动部署网页

on:
  push:
    branches: [ version1.0.0 ] # 当你把代码推送到 main 分支时触发

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 安装依赖
        run: npm install

      - name: 打包项目
        run: npm run build

      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Vite 默认打包出来的文件夹是 dist

      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4